- hosts: all
  remote_user: ubuntu
  sudo: yes
  vars:
    download_url: http://www-eu.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
    download_folder: /usr/local
    maven_name: "{{download_folder}}/apache-maven-3.5.2"
    maven_archive: "{{download_folder}}/apache-maven-3.5.2-bin.tar.gz"


  tasks:

  - name: Create directory structure
    command: mkdir -p {{download_folder}}
    command: mkdir -p {{maven_name}} 

  - name: Download Maven
    get_url: url={{download_url}} dest={{maven_name}}

  - name: Unpack archive
    unarchive: 
      src: "{{maven_archive}}"
      dest: "{{download_folder}}"
      remote_src: yes


  #Create environment variables

  - name: Create file
    command: touch /etc/profile.d/maven.sh
    args:
    creates: /etc/profil.d/maven.sh

  - lineinfile:
     path: /etc/profile.d/maven.sh
     state: present
     line: 'export M2_HOME=/usr/local/maven'

  - lineinfile:
     path: /etc/profile.d/maven.sh
     state: present
     line: 'export PATH=${M2_HOME}/bin:${PATH}'

  - name: Load environment variables
    shell: 'source /etc/profile.d/maven.sh'